url: https://convox.com

kramdown:
  input: GFM

permalink: /blog/:title/

collections:
  introduction:
    title: Introduction
    output: true
    permalink: /docs/:name/
  development:
    title: Development
    output: true
    permalink: /docs/:name/
  deployment:
    title: Deployment
    output: true
    permalink: /docs/:name/
  management:
    title: Management
    output: true
    permalink: /docs/:name/
  monitoring:
    title: Monitoring
    output: true
    permalink: /docs/:name/
  services:
    title: Services
    output: true
    permalink: /docs/:name/
  languages:
    title: Languages & Frameworks
    output: true
    permalink: /docs/:name/
  reference:
    title: Reference
    output: true
    permalink: /docs/:name/
  help:
    title: Help
    output: true
    permalink: /docs/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: main
      subnav: none
  - scope:
      type: posts
    values:
      layout: post
      subnav: blog
  - scope:
      path: api
    values:
      subnav: api
  - scope:
      path: blog
    values:
      subnav: blog
  - scope:
      path: docs
    values:
      layout: docs
      subnav: docs
  - scope:
      path: team
    values:
      subnav: team
  - scope:
      path: jobs
    values:
      layout: jobs
      subnav: jobs
